on:
  workflow_dispatch:
  schedule:
  - cron: "0 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eco4cast/rocker-neon4cast
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
# Point to the right path, run the right Rscript command
      - name: Run ensemble generation
        run: Rscript Models/generate_ensembles.R 
