on:
  workflow_dispatch:
  schedule:
  - cron: "0 23 * * *"

jobs:
  baseline_ensemble:
    runs-on: ubuntu-latest
    container:
      image: eco4cast/rocker-neon4cast
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run ensemble generation
        run: Rscript Models/baseline_ensemble.R 
  
  fARIMA_clim_ensemble:
    runs-on: ubuntu-latest
    container:
      image: eco4cast/rocker-neon4cast
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run ensemble generation
        run: Rscript Models/fARIMA_clim_ensemble.R       

  ler_ensemble:
    runs-on: ubuntu-latest
    container:
      image: eco4cast/rocker-neon4cast
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run ensemble generation
        run: Rscript Models/flare_ler_ensemble.R   
        
  ler_baseline_ensemble:
    runs-on: ubuntu-latest
    container:
      image: eco4cast/rocker-neon4cast
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run ensemble generation
        run: Rscript Models/ler_baselines_ensemble.R 
  
  phenology_ensembles:
    runs-on: ubuntu-latest
    container:
      image: eco4cast/rocker-neon4cast
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run ensemble generation
        run: Rscript Models/phenology_ensembles.R 
  
